
server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  main:
    allow-circular-references: true
  profiles:
    include:
    - oauth2  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hts?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: htsDev
    password: htsDev1234!
    
  jpa:
    hibernate:
      ddl-auto: update # create update 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true   
   
  jackson:
    serialization:
      fail-on-empty-beans: false
      
mybatis:
  configuration:
      multiple-result-sets-enabled: false    
      map-underscore-to-camel-case: true    
      call-setters-on-nulls: true        
      jdbc-type-for-null: varchar    
      default-fetch-size: 500  
      
logging:
  level: 
    root: info
    '[com.hyun]': debug 
    
# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용 (아래 명령어를 터미널에 쳐보면 그대로 나옴)
# $ echo 'spring-boot-security-jwt-tutorial-jiwoon-spring-boot-security-jwt-tutorial' | base64
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK